# Generated by Django 3.2 on 2021-05-02 11:05

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='ques',
        ),
    ]
