# Generated by Django 3.2 on 2021-05-03 09:13

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210502_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=jsonfield.fields.JSONField(default='[\n  {\n    "Value": " ",\n    "Answer": false\n  },\n  {\n    "Value": " ",\n    "Answer": false\n  },\n  {\n    "Value": " ",\n    "Answer": false\n  },\n  {\n    "Value": " ",\n    "Answer": false\n  }\n]'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=5),
        ),
    ]
